### ISSUE TITLE
Open/close system data collection

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1228]
The data about whether the property is an open or closed system is taken on step 2 of data collection, which should be moved to this step because it is on a property level 
![image](https://github.com/kartoza/sawps/assets/90245715/811bba9b-eb19-4df1-a83e-d19b0f4c83de)
Then displayed here, the column should be renamed accordingly.
![image](https://github.com/kartoza/sawps/assets/90245715/efe6da59-8c21-493c-9f62-a20751a21882)

**Comment by zamuzakki** [comment]
@LunaAsefaw I've made PR for this.
- [ ] Move Open/Close System input to Property form
- [ ] Update "Open" header in property report to "Open Close System"

The header is `Open Close System` instead of `Open/Close System` because the frontend converts the header automatically from the property (`open_close_system`)

**Comment by LunaAsefaw** [comment]
@zamuzakki is this fixed for the new records or doe this provide a fix for records that already exist?

**Comment by danangmassandy** [comment]
@LunaAsefaw @zamuzakki could you let me know what's the pending to do for this ticket?

**Comment by LunaAsefaw** [comment]
@zamuzakki this issue is resolved, sorry for the delay
