### ISSUE TITLE
Draw choropleth layer for province based on species count

### ISSUE THREAD

**Issue by danangmassandy** [kartoza/sawps#1274]
This is part of [Filter by species on map tab](https://github.com/kartoza/sawps/issues/934)

**Comment by LunaAsefaw** [comment]
@danangmassandy if I am not mistaken, this shows the sum of all the difference year's records right? 

![Image](https://github.com/kartoza/sawps/assets/90245715/63c2c613-1cc5-4acf-9dc5-0068810db91b)

![Image](https://github.com/kartoza/sawps/assets/90245715/f7467b0c-56a7-4a68-973c-c9315b667936)

I think this is misleading because if I had 20 elephants this year and 21 last year, the map will show 41 for my province, which is not true @amyburness @timlinux

**Comment by danangmassandy** [comment]
Yes, current logic will sum data for all years. Please let me know the correct logic then I can change it.

**Comment by danangmassandy** [comment]
Linked to #1580 to change the query for the population data from end year filter only.

**Comment by LunaAsefaw** [comment]
Will pass ticket when 1580 is implemented
