### ISSUE TITLE
Filter issue: Data contributors/organisational members and managers should not see filter by organisation

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1395]
Currently this is my user role:
![image](https://github.com/kartoza/sawps/assets/90245715/edb6cd10-5160-42ef-8458-085f98850dcf)
But I still see organisation filter:
![image](https://github.com/kartoza/sawps/assets/90245715/85c24de3-275e-4a15-b8cf-772803ba5a71)

Organisation filter is only applicable for data scientists and data consumers

**Comment by zamuzakki** [comment]
Organisation filter is only applicable for data scientists and data consumers
But you also have Super User, which technically could do anything.

**Comment by LunaAsefaw** [comment]
ahhh I see, the organisation filter does not show when I am not a super user but that now shows a new issue: There are 68 properties on the system (that is the amount I see as a super user that can access everything) but when I log in as a regular user, I do not see the organisation (good) but I see all the properties that exist on the system, even though I am just an organisational member who should only access data relating to the organisation I belong to
![image](https://github.com/kartoza/sawps/assets/90245715/d4cf5d14-ee52-42fb-ba2d-acd2d0e7ab61)

**Comment by zamuzakki** [comment]
@LunaAsefaw I don't know how it should behave and how it was designed/the logic, but what happend here is this:
Your active organisation is CapeNature, which is a national organisation. Hence, it can see all property.

I tried updating your organisation to `Eastern Cape Department of Economic Development, Environmental Affairs and Tourism`, but since its province is `None`, all organisation with province `None` is returned. This, in return would also cause many properties to be returned.

**Comment by LunaAsefaw** [comment]
Update: Zakki and I met to discuss this issue.
