### ISSUE TITLE
Change map population query to use end year filter

### ISSUE THREAD

**Issue by danangmassandy** [kartoza/sawps#1580]
This ticket is for #1574. We need to change the map query to use end year filter only instead of using both start and end year.

**Comment by LunaAsefaw** [comment]
@danangmassandy I am not sure if this is implemented yet since the filter is still the same but I see it is in the needs review columm. 
I see that it still shows the accumulated amount because if it is based of the last year on the filter then when the range is 2013-2013, the data should be the same as when it is 1960-2013 because the data would only be for the last year on the selected filter. 

https://github.com/kartoza/sawps/assets/90245715/7c2a5efb-87b6-44b8-8b6e-c6e1344c81e2

**Comment by danangmassandy** [comment]
Hi Luna, the PR is not merged yet so the changes are not deployed to staging. I will update you once Dimas merge the PR and this change has been deployed to staging.

**Comment by danangmassandy** [comment]
@LunaAsefaw the changes have been deployed to staging.
