### ISSUE TITLE
Property trend charts should be removed when no properties selected

### ISSUE THREAD

**Issue by timlinux** [kartoza/sawps#1667]
![Peek 2023-11-20 08-55](https://github.com/kartoza/sawps/assets/178003/91b057c6-4afa-45be-9413-aea1afd0c7ee)

**Comment by timlinux** [comment]
And title should be 'Properties' not 'Property' if there are multiple properties selected.

**Comment by LunaAsefaw** [comment]
@danangmassandy @timlinux 

https://github.com/kartoza/sawps/assets/90245715/5f8c37e4-dc1e-470d-b493-bf13df46460d

 This might be a bad UX but I was wondering if we should put up some message when the property has no data instead of leaving the whole property section hidden, maybe some heads up to users that it is not that the site is not responding, there is just no data here. Additionally, we have used an approach with the other filters: when there is no data for something, it is not part of the dropdown values. However, that might also make people report issues saying their property is not listed. So currently I would like to know if just the text/disclaimer would be useful.

Additionally, @danangmassandy can we pivot the filters tab so even if I scroll down, the filtes tab is floating/sticky on its section of the area so I don't have to scroll up and down to see my filters then again my charts. This is the same proposal for all the other tabs

**Comment by danangmassandy** [comment]
@LunaAsefaw I also agree with adding text when there is no selected property. Could you suggest for the text please?

For the sticky filter, I've created [a ticket](https://github.com/kartoza/sawps/issues/1756) and will work on it.
