### ISSUE TITLE
Push notification functionality for reminders

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#696]
❗ Issue
Currently users views reminders when on that page, thus some reminders may be missed.

💡 Solution
Some indication of pending reminders, perhaps when user logs in they are notified of the amount of reminders they have and if they'd like to view them

**Comment by amyburness** [comment]
@DONOTFORGET-BYTE 

Keen the workflow for the new notifications with the bell on the profile picture. can we possibly add the number of notifications the user has received since they last logged in and clicked on the notification bell?  when the user clicks on the bell they get a list of all the notifications and reminders that they can then click on and will be direct to the notification or reminder in the profile environment. 

Can we then also add the bell with the number of reminders and notifications tabs when in the profile pages? 
![image](https://github.com/kartoza/sawps/assets/77841514/660bdac6-6c4b-4f2c-8082-dc9ee0f3eef3)

**Comment by DONOTFORGET-BYTE** [comment]
@amyburness the bell on the reminders .what's the logic behind it ? is it like reminders that are close like a 15 min before or ?
