### ISSUE TITLE
I can't see the organisation: when in the profile area

### ISSUE THREAD

**Issue by amyburness** [kartoza/sawps#736]
@tinashechiraya Please show the organization in this dropdown. The dropdown Sould be consistent throughout the site. 
![image](https://github.com/kartoza/sawps/assets/77841514/faf802c7-db48-42dd-86e7-2f14a9d67d2b)

**Comment by tinashechiraya** [comment]
on the profile page and 2fa page the organisation is not going to be available so I have hidden it from the dropdown when you're on those 2 pages ...it is however available on pages like reminders and notifications where you need to switch organisations to see their specific reminders etc. The reason its not available on the 2fa is because this page uses a package and a few custom methods that I added for 2fa authentication thus it cannot inherit the view that makes the organisation available. The profile page can inherit but I would have to change the structure of the view because currently it returns an object that has the user details in it ,so If I inherit the view for the organisation that object is no longer available so I'll have to change its implementation which will take a little time maybe size 3 ,so should I proceed with that ?

**Comment by amyburness** [comment]
Hi there no, this would be a nice to have so focus on other tickets for now and we will park this ticket for later.
