### ISSUE TITLE
Styling for the national level map

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#787]
We need styling for the national map so a map for all of SA highlighted and styling for provinces. Remember to use the SANBI colours.

**Comment by LunaAsefaw** [comment]
cc @amyburness

**Comment by Jeremy-Prior** [comment]
Used the SANBI Orange (Hex: faa755) as the highlight colour. The max zoom level for the nationa,l and regional styles, is level 7 as otherwise cadastral information started to render.

**Light Mode**: 
- Initial overview is the same as the normal map
   ![issue787_1](https://github.com/kartoza/sawps/assets/100694811/c45adb45-5460-48b2-b4ba-c6fb88a37b2a)

- Highlighted ZAF
   ![issue787_2](https://github.com/kartoza/sawps/assets/100694811/b44cc2d7-1e73-4dd3-946d-0cea58d7c020)

- Highlighted Gauteng at min zoom level
   ![issue787_3](https://github.com/kartoza/sawps/assets/100694811/9bbf572f-aca2-43c4-a362-0f05566f502d)

- Highlighted Gauteng at max zoom level
   ![issue787_4](https://github.com/kartoza/sawps/assets/100694811/6836374d-ce9e-429f-b6cc-03250c188631)

**Dark Mode**:
- Initial overview is the same as the normal map
   ![issue787_5](https://github.com/kartoza/sawps/assets/100694811/963fa16c-2de2-4488-b0e3-d68e9011cee3)

- Highlighted ZAF
   ![issue787_6](https://github.com/kartoza/sawps/assets/100694811/598c6f54-6dfd-47e9-8bc9-f4774dd66639)

- Highlighted Gauteng at min zoom level
   ![issue787_7](https://github.com/kartoza/sawps/assets/100694811/b79315f2-d9f8-404a-897e-9d2e780146e9)

- Highlighted Gauteng at max zoom level
   ![issue787_8](https://github.com/kartoza/sawps/assets/100694811/4ad305d4-9b9c-4ac3-b6a5-464be612fb8d)
