### ISSUE TITLE
Issue with setting up 2FA as a new user

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#858]
when registering as a new user, I am asked to set up my 2FA. But when I input the token, it still takes me to the same page and continues to ask for my token but does not show any error message. 
Not sure if this helps:

![Image](https://user-images.githubusercontent.com/90245715/262304706-22b35eff-36c9-41ac-91d1-3132e337b4c8.png)

**Comment by LunaAsefaw** [comment]
https://github.com/kartoza/sawps/assets/90245715/85c39bff-1a5c-4e01-a902-842a3a793404

**Comment by tinashechiraya** [comment]
@LunaAsefaw I just tried registering a new account from my other emails. I did not experience this ,can you retry , If you're using an authenticator app from your phone ,make sure the picture is clear because sometimes when it just quickly scans the the barcode it captures incorrectly and that can lead to that error ,but when a picture is taken clearly it should allow you through . If you experience this problem again can you give me the steps to reproduce that problem then I'll take it from there thanks
