### ISSUE TITLE
Download charts functionality

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#919]
When user clicks on 'download visualisation', this will prompt a pop up that asks the users to select which charts to download. Multiselect is allowed

![Image](https://user-images.githubusercontent.com/90245715/264636948-00d4d099-5489-4af0-a1c9-4b953e0cd875.png)

**Comment by tinashechiraya** [comment]
@LunaAsefaw is this for the data contributors only or its for the current download data visuals that is there ,that was done by Ketan?

**Comment by amyburness** [comment]
HI there this is functionality that should be available to all levels of user, if they click on a chart (any chart) then they should get a popup allowing them to download that specific chart.  Perhaps we put a small download button on each chart that the user can click on instead of the whole chart being clickable for the download popup. @ketankartoza may need to add that. The button must just be a download symbol, not the word. 

The button allowing multiple chart downloads at the bottom of the page can stay as it is still useful for the user.
